language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'
  - '6'
sudo: false
script:
  - "npm run test-cov"
after_script: "npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
